name: CI

on:
  push:
  pull_request:
    branches:
      - v1.x

defaults:
  run:
    shell: bash

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: VS2022 x86 Development
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x86
            configuration: Development
          - name: VS2022 x86 Release
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x86
            configuration: Release
          - name: VS2022 x64 Development
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x64
            configuration: Development
          - name: VS2022 x64 Release
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x64
            configuration: Release
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5

    - name: Install VSSetup
      run: Install-Module VSSetup -Scope CurrentUser
      shell: powershell

    - name: Show installed toolsets
      run: |
        echo "--- All:"
        Get-VSSetupInstance -All
        echo "--- VC140:"
        Get-VSSetupInstance -All | Select-VSSetupInstance -Latest -Require Microsoft.VisualStudio.Component.VC.140
      shell: powershell

      # try powershell command from https://github.com/actions/runner-images/issues/9873#issuecomment-2139288682
    - if: matrix.toolset == 'v140'
      name: Install VC.140 components
      run: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToRemove= @(
        "Microsoft.VisualStudio.Component.VC.140"
        "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
        )
        [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        # should be run twice
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      shell: powershell

    - if: matrix.toolset == 'v140'
      name: Show installed toolsets
      run: |
        echo "--- All:"
        Get-VSSetupInstance -All
        echo "--- VC140:"
        Get-VSSetupInstance -All | Select-VSSetupInstance -Latest -Require Microsoft.VisualStudio.Component.VC.140
      shell: powershell

#       # try install-vs-components python script
#     - if: matrix.toolset == 'v140'
#       name: Install missing Visual Studio components
#       run: python .github/workflows/install-vs-components.py
# 
#     - if: matrix.toolset == 'v140'
#       name: Show installed toolsets
#       run: |
#         echo "--- All:"
#         Get-VSSetupInstance -All
#         echo "--- VC140:"
#         Get-VSSetupInstance -All | Select-VSSetupInstance -Latest -Require Microsoft.VisualStudio.Component.VC.140
#       shell: powershell
# 
#       # try command from https://github.com/actions/runner-images/issues/9873#issuecomment-2833115951
#     - if: matrix.toolset == 'v140'
#       name: Install missing Visual Studio components
#       run: |
#         Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
#         $VsInstallPath = vswhere.exe -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
#         [string]$ComponentsToAdd = @(
#         "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
#         "Microsoft.VisualStudio.Component.VC.140"
#         ) | ForEach-Object {"--add $_"}
#         $ArgumentList = ('modify', '--installPath', "`"$VsInstallPath`"", $ComponentsToAdd, '--quiet', '--norestart', '--nocache')
#         echo "vs_installer.exe $($ArgumentList -join ' ')"
#         # should be run twice for some reason
#         Start-Process -FilePath vs_installer.exe -ArgumentList $ArgumentList -Wait -PassThru -WindowStyle Hidden
#         Start-Process -FilePath vs_installer.exe -ArgumentList $ArgumentList -Wait -PassThru -WindowStyle Hidden
#       shell: powershell
# 
#     - if: matrix.toolset == 'v140'
#       name: Show installed toolsets
#       run: |
#         echo "--- All:"
#         Get-VSSetupInstance -All
#         echo "--- VC140:"
#         Get-VSSetupInstance -All | Select-VSSetupInstance -Latest -Require Microsoft.VisualStudio.Component.VC.140
#       shell: powershell
# 
#       # try winget
#     - if: matrix.toolset == 'v140'
#       name: Show installed toolsets
#       run: winget install --accept-package-agreements --accept-source-agreements Microsoft.BuildTools2015
#     
#     - if: matrix.toolset == 'v140'
#       name: Show installed toolsets
#       run: |
#         echo "--- All:"
#         Get-VSSetupInstance -All
#         echo "--- VC140:"
#         Get-VSSetupInstance -All | Select-VSSetupInstance -Latest -Require Microsoft.VisualStudio.Component.VC.140
#       shell: powershell
# 
#       # try chocolatey
#     - if: matrix.toolset == 'v140'
#       name: Show installed toolsets
#       run: choco install visualcppbuildtools
# 
#     - if: matrix.toolset == 'v140'
#       name: Show installed toolsets
#       run: |
#         echo "--- All:"
#         Get-VSSetupInstance -All
#         echo "--- VC140:"
#         Get-VSSetupInstance -All | Select-VSSetupInstance -Latest -Require Microsoft.VisualStudio.Component.VC.140
#       shell: powershell

    - name: Download optional 3rdparty extras
      run: |
        curl https://renderdoc.org/qrenderdoc_3rdparty.zip -O
        7z x qrenderdoc_3rdparty.zip
    - name: Set up Visual Studio tools
      uses: microsoft/setup-msbuild@v2
    - name: Building solution
      run: msbuild.exe renderdoc.sln -p:UseMultiToolTask=true "/p:Configuration=${{ matrix.configuration }}" "/p:Platform=${{ matrix.platform }}" "/p:PlatformToolset=${{ matrix.toolset }}"
      shell: powershell
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: |
          */${{ matrix.configuration }}/*
          !*/${{ matrix.configuration }}/obj*
          !*/${{ matrix.configuration }}/pymodules*
          !*/${{ matrix.configuration }}/*.ilk
          !*/${{ matrix.configuration }}/*.exp
          !*/${{ matrix.configuration }}/*.lib
          !*/${{ matrix.configuration }}/driver*.pdb
    - if: matrix.configuration == 'Development'
      name: Running core unit tests
      run: |
        if ! ./*/Development/renderdoccmd.exe test unit -o test.log; then
          echo "::error::$(cat test.log)" | tr -d '\r' |  tr '\n' '\001' | sed -e 's#\x01#%0D%0A#g';
          exit 1;
        fi
    - if: matrix.configuration == 'Development'
      name: Running UI unit tests
      run: |
        if ! ./*/Development/qrenderdoc.exe --unittest log=test.log; then
          echo "::error::$(cat test.log)" | tr -d '\r' |  tr '\n' '\001' | sed -e 's#\x01#%0D%0A#g';
          exit 1;
        fi
