name: CI

on:
  push:
  pull_request:
    branches:
      - v1.x

defaults:
  run:
    shell: bash

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: VS2022 x86 Development
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x86
            configuration: Development
          - name: VS2022 x86 Release
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x86
            configuration: Release
          - name: VS2022 x64 Development
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x64
            configuration: Development
          - name: VS2022 x64 Release
            os: windows-2025
            compiler: VS2022
            toolset: v143
            platform: x64
            configuration: Release
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - uses: mxschmitt/action-tmate/detached@v3
      if: matrix.configuration == 'Development' && matrix.platform == 'x64'

    - name: Download optional 3rdparty extras
      run: |
        set -eux
        curl https://renderdoc.org/qrenderdoc_3rdparty.zip -O
        7z x qrenderdoc_3rdparty.zip
        curl -o python-setup.exe -L https://www.python.org/ftp/python/3.13.5/python-3.13.5${{ matrix.platform == 'x64' && '-amd64' || ''  }}.exe
    - name: Prepare Python
      run: |
        Start-Process -FilePath ./python-setup.exe -ArgumentList '/quiet InstallAllUsers=0 PrependPath=1 Include_test=0 Include_pip=1 TargetDir=C:\Python313' -Wait
        cd C:\Python313
        Compress-Archive -Path .\Lib\* -DestinationPath .\python313.zip
      shell: powershell
    - name: Set up Visual Studio tools
      uses: microsoft/setup-msbuild@v2
    - name: Building solution
      run: msbuild.exe renderdoc.sln -p:UseMultiToolTask=true "/p:Configuration=${{ matrix.configuration }}" "/p:Platform=${{ matrix.platform }}" "/p:PlatformToolset=${{ matrix.toolset }}" "/p:VSPythonOverridePath=C:\Python313"
      shell: powershell
    - run: |
        cd docs
        python regenerate_stubs.py ../stubs || true
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: |
          stubs
          */${{ matrix.configuration }}/*
          !*/${{ matrix.configuration }}/obj*
          !*/${{ matrix.configuration }}/*.ilk
          !*/${{ matrix.configuration }}/*.exp
          !*/${{ matrix.configuration }}/*.lib
          !*/${{ matrix.configuration }}/driver*.pdb
    - if: matrix.configuration == 'Development'
      name: Running core unit tests
      run: |
        if ! ./*/Development/renderdoccmd.exe test unit -o test.log; then
          echo "::error::$(cat test.log)" | tr -d '\r' |  tr '\n' '\001' | sed -e 's#\x01#%0D%0A#g';
          exit 1;
        fi
    - if: matrix.configuration == 'Development'
      name: Running UI unit tests
      run: |
        if ! ./*/Development/qrenderdoc.exe --unittest log=test.log; then
          echo "::error::$(cat test.log)" | tr -d '\r' |  tr '\n' '\001' | sed -e 's#\x01#%0D%0A#g';
          exit 1;
        fi
