name: Copilot Setup Verification

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  copilot-setup-test:
    name: Copilot Setup Test
    runs-on: ubuntu-22.04
    env:
      QT_SELECT: qt5
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - name: Install compilation dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev mesa-common-dev libgl1-mesa-dev qtbase5-dev libqt5svg5-dev libqt5x11extras5-dev libxcb-keysyms1-dev libx11-xcb-dev g++-11 libpcre3-dev xvfb
    - name: Build
      run: |
        mkdir build
        pushd build
        CC=gcc-11 CXX=g++-11 cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-g -Wno-implicit-fallthrough" ..
        make -j2
        popd
    - name: Run core unit tests
      run: |
        if ! ./build/bin/renderdoccmd test unit -o test.log; then
          echo "::error::$(cat test.log)" | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
          exit 1;
        fi
    - name: Run UI unit tests
      run: |
        if ! xvfb-run -a ./build/bin/qrenderdoc --unittest log=test.log; then
          echo "::error::$(cat test.log)" | tr '\n' '\001' | sed -e 's#\x01#%0A#g';
          exit 1;
        fi